### ISSUE TITLE
Bază de date relațională

### ISSUE THREAD

**Issue by eduardbudacu** [skls1337/anonymous-grading-app#5]
Vă rog să consultați specificațiile generale pentru modul de stocare al datelor

- Stocarea se va face peste o bază relațională și accesul la baza se va face prin intermediul unui ORM

https://docs.google.com/document/d/1j__6YlOQFNxxRjrA73jXyNfBI0M-OHwD6U3Ueqlmmbg/edit

**Comment by skls1337** [comment]
Am luat la cunostinta specificatiile, stim ca baza de date a proiectului nu este relationala, tip ORM. Dorim sa continuam cu backend-ul pe care il avem acum si suntem constienti ca vom fi depunctati pe aceasta parte la nota finala.
